// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/shardkv.proto

package kvrpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 错误码枚举
type ErrorCode int32

const (
	ErrorCode_OK               ErrorCode = 0
	ErrorCode_ERR_NO_KEY       ErrorCode = 1 // key 不存在
	ErrorCode_ERR_WRONG_GROUP  ErrorCode = 2 // 请求的 key 不属于当前 Group（分片不在这里）
	ErrorCode_ERR_WRONG_LEADER ErrorCode = 3 // 当前节点不是 Leader，需要重试其他节点
	ErrorCode_ERR_TIMEOUT      ErrorCode = 4 // 请求超时
	ErrorCode_ERR_WRONG_CONFIG ErrorCode = 5 // 配置版本不匹配
	ErrorCode_ERR_NOT_READY    ErrorCode = 6 // 服务未就绪
	ErrorCode_ERR_INTERNAL     ErrorCode = 7 // 内部错误
)

// Enum value maps for ErrorCode.
var (
	ErrorCode_name = map[int32]string{
		0: "OK",
		1: "ERR_NO_KEY",
		2: "ERR_WRONG_GROUP",
		3: "ERR_WRONG_LEADER",
		4: "ERR_TIMEOUT",
		5: "ERR_WRONG_CONFIG",
		6: "ERR_NOT_READY",
		7: "ERR_INTERNAL",
	}
	ErrorCode_value = map[string]int32{
		"OK":               0,
		"ERR_NO_KEY":       1,
		"ERR_WRONG_GROUP":  2,
		"ERR_WRONG_LEADER": 3,
		"ERR_TIMEOUT":      4,
		"ERR_WRONG_CONFIG": 5,
		"ERR_NOT_READY":    6,
		"ERR_INTERNAL":     7,
	}
)

func (x ErrorCode) Enum() *ErrorCode {
	p := new(ErrorCode)
	*p = x
	return p
}

func (x ErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_shardkv_proto_enumTypes[0].Descriptor()
}

func (ErrorCode) Type() protoreflect.EnumType {
	return &file_proto_shardkv_proto_enumTypes[0]
}

func (x ErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorCode.Descriptor instead.
func (ErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_proto_shardkv_proto_rawDescGZIP(), []int{0}
}

// Get 请求
type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_proto_shardkv_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shardkv_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_proto_shardkv_proto_rawDescGZIP(), []int{0}
}

func (x *GetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

// Get 响应
type GetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Err           ErrorCode              `protobuf:"varint,1,opt,name=err,proto3,enum=shardkv.ErrorCode" json:"err,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_proto_shardkv_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shardkv_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_proto_shardkv_proto_rawDescGZIP(), []int{1}
}

func (x *GetResponse) GetErr() ErrorCode {
	if x != nil {
		return x.Err
	}
	return ErrorCode_OK
}

func (x *GetResponse) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// PutAppend 请求
type PutAppendRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Op            int32                  `protobuf:"varint,3,opt,name=op,proto3" json:"op,omitempty"` // "Put" 或 "Append"
	ClientId      int64                  `protobuf:"varint,4,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	SeqId         int64                  `protobuf:"varint,5,opt,name=seq_id,json=seqId,proto3" json:"seq_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutAppendRequest) Reset() {
	*x = PutAppendRequest{}
	mi := &file_proto_shardkv_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutAppendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutAppendRequest) ProtoMessage() {}

func (x *PutAppendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shardkv_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutAppendRequest.ProtoReflect.Descriptor instead.
func (*PutAppendRequest) Descriptor() ([]byte, []int) {
	return file_proto_shardkv_proto_rawDescGZIP(), []int{2}
}

func (x *PutAppendRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *PutAppendRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *PutAppendRequest) GetOp() int32 {
	if x != nil {
		return x.Op
	}
	return 0
}

func (x *PutAppendRequest) GetClientId() int64 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

func (x *PutAppendRequest) GetSeqId() int64 {
	if x != nil {
		return x.SeqId
	}
	return 0
}

// PutAppend 响应
type PutAppendResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Err           ErrorCode              `protobuf:"varint,1,opt,name=err,proto3,enum=shardkv.ErrorCode" json:"err,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutAppendResponse) Reset() {
	*x = PutAppendResponse{}
	mi := &file_proto_shardkv_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutAppendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutAppendResponse) ProtoMessage() {}

func (x *PutAppendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shardkv_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutAppendResponse.ProtoReflect.Descriptor instead.
func (*PutAppendResponse) Descriptor() ([]byte, []int) {
	return file_proto_shardkv_proto_rawDescGZIP(), []int{3}
}

func (x *PutAppendResponse) GetErr() ErrorCode {
	if x != nil {
		return x.Err
	}
	return ErrorCode_OK
}

// 分片操作请求（用于迁移和GC）
type ShardOperationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConfigNum     int32                  `protobuf:"varint,1,opt,name=config_num,json=configNum,proto3" json:"config_num,omitempty"`
	ShardIds      []int32                `protobuf:"varint,2,rep,packed,name=shard_ids,json=shardIds,proto3" json:"shard_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShardOperationRequest) Reset() {
	*x = ShardOperationRequest{}
	mi := &file_proto_shardkv_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShardOperationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShardOperationRequest) ProtoMessage() {}

func (x *ShardOperationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shardkv_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShardOperationRequest.ProtoReflect.Descriptor instead.
func (*ShardOperationRequest) Descriptor() ([]byte, []int) {
	return file_proto_shardkv_proto_rawDescGZIP(), []int{4}
}

func (x *ShardOperationRequest) GetConfigNum() int32 {
	if x != nil {
		return x.ConfigNum
	}
	return 0
}

func (x *ShardOperationRequest) GetShardIds() []int32 {
	if x != nil {
		return x.ShardIds
	}
	return nil
}

// 分片操作响应
type ShardOperationResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Err   ErrorCode              `protobuf:"varint,1,opt,name=err,proto3,enum=shardkv.ErrorCode" json:"err,omitempty"`
	// 以下只用于 ShardMigration
	ConfigNum      int32                        `protobuf:"varint,2,opt,name=config_num,json=configNum,proto3" json:"config_num,omitempty"`
	ShardData      map[int32]*ShardData         `protobuf:"bytes,3,rep,name=shard_data,json=shardData,proto3" json:"shard_data,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	DuplicateTable map[int64]*LastOperationInfo `protobuf:"bytes,4,rep,name=duplicate_table,json=duplicateTable,proto3" json:"duplicate_table,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ShardOperationResponse) Reset() {
	*x = ShardOperationResponse{}
	mi := &file_proto_shardkv_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShardOperationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShardOperationResponse) ProtoMessage() {}

func (x *ShardOperationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shardkv_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShardOperationResponse.ProtoReflect.Descriptor instead.
func (*ShardOperationResponse) Descriptor() ([]byte, []int) {
	return file_proto_shardkv_proto_rawDescGZIP(), []int{5}
}

func (x *ShardOperationResponse) GetErr() ErrorCode {
	if x != nil {
		return x.Err
	}
	return ErrorCode_OK
}

func (x *ShardOperationResponse) GetConfigNum() int32 {
	if x != nil {
		return x.ConfigNum
	}
	return 0
}

func (x *ShardOperationResponse) GetShardData() map[int32]*ShardData {
	if x != nil {
		return x.ShardData
	}
	return nil
}

func (x *ShardOperationResponse) GetDuplicateTable() map[int64]*LastOperationInfo {
	if x != nil {
		return x.DuplicateTable
	}
	return nil
}

// 分片数据
type ShardData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kv            map[string]string      `protobuf:"bytes,1,rep,name=kv,proto3" json:"kv,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShardData) Reset() {
	*x = ShardData{}
	mi := &file_proto_shardkv_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShardData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShardData) ProtoMessage() {}

func (x *ShardData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shardkv_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShardData.ProtoReflect.Descriptor instead.
func (*ShardData) Descriptor() ([]byte, []int) {
	return file_proto_shardkv_proto_rawDescGZIP(), []int{6}
}

func (x *ShardData) GetKv() map[string]string {
	if x != nil {
		return x.Kv
	}
	return nil
}

// 最后操作信息（用于去重），只用于 RPC 响应中传递，业务处理时需转为 common 中的 LastOperationInfo
type LastOperationInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SeqId         int64                  `protobuf:"varint,1,opt,name=seq_id,json=seqId,proto3" json:"seq_id,omitempty"`
	Reply         *OpReply               `protobuf:"bytes,2,opt,name=reply,proto3" json:"reply,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LastOperationInfo) Reset() {
	*x = LastOperationInfo{}
	mi := &file_proto_shardkv_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LastOperationInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LastOperationInfo) ProtoMessage() {}

func (x *LastOperationInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shardkv_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LastOperationInfo.ProtoReflect.Descriptor instead.
func (*LastOperationInfo) Descriptor() ([]byte, []int) {
	return file_proto_shardkv_proto_rawDescGZIP(), []int{7}
}

func (x *LastOperationInfo) GetSeqId() int64 {
	if x != nil {
		return x.SeqId
	}
	return 0
}

func (x *LastOperationInfo) GetReply() *OpReply {
	if x != nil {
		return x.Reply
	}
	return nil
}

// 操作回复，只用于 RPC 响应中传递，业务处理时需转为 common 中的 OpReply
type OpReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Err           ErrorCode              `protobuf:"varint,2,opt,name=err,proto3,enum=shardkv.ErrorCode" json:"err,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpReply) Reset() {
	*x = OpReply{}
	mi := &file_proto_shardkv_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpReply) ProtoMessage() {}

func (x *OpReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shardkv_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpReply.ProtoReflect.Descriptor instead.
func (*OpReply) Descriptor() ([]byte, []int) {
	return file_proto_shardkv_proto_rawDescGZIP(), []int{8}
}

func (x *OpReply) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *OpReply) GetErr() ErrorCode {
	if x != nil {
		return x.Err
	}
	return ErrorCode_OK
}

var File_proto_shardkv_proto protoreflect.FileDescriptor

const file_proto_shardkv_proto_rawDesc = "" +
	"\n" +
	"\x13proto/shardkv.proto\x12\ashardkv\"\x1e\n" +
	"\n" +
	"GetRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"I\n" +
	"\vGetResponse\x12$\n" +
	"\x03err\x18\x01 \x01(\x0e2\x12.shardkv.ErrorCodeR\x03err\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"~\n" +
	"\x10PutAppendRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12\x0e\n" +
	"\x02op\x18\x03 \x01(\x05R\x02op\x12\x1b\n" +
	"\tclient_id\x18\x04 \x01(\x03R\bclientId\x12\x15\n" +
	"\x06seq_id\x18\x05 \x01(\x03R\x05seqId\"9\n" +
	"\x11PutAppendResponse\x12$\n" +
	"\x03err\x18\x01 \x01(\x0e2\x12.shardkv.ErrorCodeR\x03err\"S\n" +
	"\x15ShardOperationRequest\x12\x1d\n" +
	"\n" +
	"config_num\x18\x01 \x01(\x05R\tconfigNum\x12\x1b\n" +
	"\tshard_ids\x18\x02 \x03(\x05R\bshardIds\"\xbb\x03\n" +
	"\x16ShardOperationResponse\x12$\n" +
	"\x03err\x18\x01 \x01(\x0e2\x12.shardkv.ErrorCodeR\x03err\x12\x1d\n" +
	"\n" +
	"config_num\x18\x02 \x01(\x05R\tconfigNum\x12M\n" +
	"\n" +
	"shard_data\x18\x03 \x03(\v2..shardkv.ShardOperationResponse.ShardDataEntryR\tshardData\x12\\\n" +
	"\x0fduplicate_table\x18\x04 \x03(\v23.shardkv.ShardOperationResponse.DuplicateTableEntryR\x0eduplicateTable\x1aP\n" +
	"\x0eShardDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12(\n" +
	"\x05value\x18\x02 \x01(\v2\x12.shardkv.ShardDataR\x05value:\x028\x01\x1a]\n" +
	"\x13DuplicateTableEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x03R\x03key\x120\n" +
	"\x05value\x18\x02 \x01(\v2\x1a.shardkv.LastOperationInfoR\x05value:\x028\x01\"n\n" +
	"\tShardData\x12*\n" +
	"\x02kv\x18\x01 \x03(\v2\x1a.shardkv.ShardData.KvEntryR\x02kv\x1a5\n" +
	"\aKvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"R\n" +
	"\x11LastOperationInfo\x12\x15\n" +
	"\x06seq_id\x18\x01 \x01(\x03R\x05seqId\x12&\n" +
	"\x05reply\x18\x02 \x01(\v2\x10.shardkv.OpReplyR\x05reply\"E\n" +
	"\aOpReply\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\x12$\n" +
	"\x03err\x18\x02 \x01(\x0e2\x12.shardkv.ErrorCodeR\x03err*\x9a\x01\n" +
	"\tErrorCode\x12\x06\n" +
	"\x02OK\x10\x00\x12\x0e\n" +
	"\n" +
	"ERR_NO_KEY\x10\x01\x12\x13\n" +
	"\x0fERR_WRONG_GROUP\x10\x02\x12\x14\n" +
	"\x10ERR_WRONG_LEADER\x10\x03\x12\x0f\n" +
	"\vERR_TIMEOUT\x10\x04\x12\x14\n" +
	"\x10ERR_WRONG_CONFIG\x10\x05\x12\x11\n" +
	"\rERR_NOT_READY\x10\x06\x12\x10\n" +
	"\fERR_INTERNAL\x10\a2\x9e\x02\n" +
	"\aShardKV\x120\n" +
	"\x03Get\x12\x13.shardkv.GetRequest\x1a\x14.shardkv.GetResponse\x12B\n" +
	"\tPutAppend\x12\x19.shardkv.PutAppendRequest\x1a\x1a.shardkv.PutAppendResponse\x12Q\n" +
	"\x0eShardMigration\x12\x1e.shardkv.ShardOperationRequest\x1a\x1f.shardkv.ShardOperationResponse\x12J\n" +
	"\aShardGC\x12\x1e.shardkv.ShardOperationRequest\x1a\x1f.shardkv.ShardOperationResponseB\x11Z\x0f./shardkv;kvrpcb\x06proto3"

var (
	file_proto_shardkv_proto_rawDescOnce sync.Once
	file_proto_shardkv_proto_rawDescData []byte
)

func file_proto_shardkv_proto_rawDescGZIP() []byte {
	file_proto_shardkv_proto_rawDescOnce.Do(func() {
		file_proto_shardkv_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_shardkv_proto_rawDesc), len(file_proto_shardkv_proto_rawDesc)))
	})
	return file_proto_shardkv_proto_rawDescData
}

var file_proto_shardkv_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_shardkv_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_proto_shardkv_proto_goTypes = []any{
	(ErrorCode)(0),                 // 0: shardkv.ErrorCode
	(*GetRequest)(nil),             // 1: shardkv.GetRequest
	(*GetResponse)(nil),            // 2: shardkv.GetResponse
	(*PutAppendRequest)(nil),       // 3: shardkv.PutAppendRequest
	(*PutAppendResponse)(nil),      // 4: shardkv.PutAppendResponse
	(*ShardOperationRequest)(nil),  // 5: shardkv.ShardOperationRequest
	(*ShardOperationResponse)(nil), // 6: shardkv.ShardOperationResponse
	(*ShardData)(nil),              // 7: shardkv.ShardData
	(*LastOperationInfo)(nil),      // 8: shardkv.LastOperationInfo
	(*OpReply)(nil),                // 9: shardkv.OpReply
	nil,                            // 10: shardkv.ShardOperationResponse.ShardDataEntry
	nil,                            // 11: shardkv.ShardOperationResponse.DuplicateTableEntry
	nil,                            // 12: shardkv.ShardData.KvEntry
}
var file_proto_shardkv_proto_depIdxs = []int32{
	0,  // 0: shardkv.GetResponse.err:type_name -> shardkv.ErrorCode
	0,  // 1: shardkv.PutAppendResponse.err:type_name -> shardkv.ErrorCode
	0,  // 2: shardkv.ShardOperationResponse.err:type_name -> shardkv.ErrorCode
	10, // 3: shardkv.ShardOperationResponse.shard_data:type_name -> shardkv.ShardOperationResponse.ShardDataEntry
	11, // 4: shardkv.ShardOperationResponse.duplicate_table:type_name -> shardkv.ShardOperationResponse.DuplicateTableEntry
	12, // 5: shardkv.ShardData.kv:type_name -> shardkv.ShardData.KvEntry
	9,  // 6: shardkv.LastOperationInfo.reply:type_name -> shardkv.OpReply
	0,  // 7: shardkv.OpReply.err:type_name -> shardkv.ErrorCode
	7,  // 8: shardkv.ShardOperationResponse.ShardDataEntry.value:type_name -> shardkv.ShardData
	8,  // 9: shardkv.ShardOperationResponse.DuplicateTableEntry.value:type_name -> shardkv.LastOperationInfo
	1,  // 10: shardkv.ShardKV.Get:input_type -> shardkv.GetRequest
	3,  // 11: shardkv.ShardKV.PutAppend:input_type -> shardkv.PutAppendRequest
	5,  // 12: shardkv.ShardKV.ShardMigration:input_type -> shardkv.ShardOperationRequest
	5,  // 13: shardkv.ShardKV.ShardGC:input_type -> shardkv.ShardOperationRequest
	2,  // 14: shardkv.ShardKV.Get:output_type -> shardkv.GetResponse
	4,  // 15: shardkv.ShardKV.PutAppend:output_type -> shardkv.PutAppendResponse
	6,  // 16: shardkv.ShardKV.ShardMigration:output_type -> shardkv.ShardOperationResponse
	6,  // 17: shardkv.ShardKV.ShardGC:output_type -> shardkv.ShardOperationResponse
	14, // [14:18] is the sub-list for method output_type
	10, // [10:14] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_proto_shardkv_proto_init() }
func file_proto_shardkv_proto_init() {
	if File_proto_shardkv_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_shardkv_proto_rawDesc), len(file_proto_shardkv_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_shardkv_proto_goTypes,
		DependencyIndexes: file_proto_shardkv_proto_depIdxs,
		EnumInfos:         file_proto_shardkv_proto_enumTypes,
		MessageInfos:      file_proto_shardkv_proto_msgTypes,
	}.Build()
	File_proto_shardkv_proto = out.File
	file_proto_shardkv_proto_goTypes = nil
	file_proto_shardkv_proto_depIdxs = nil
}
