// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: proto/shardkv.proto

package kvrpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ShardKV_Get_FullMethodName            = "/shardkv.ShardKV/Get"
	ShardKV_PutAppend_FullMethodName      = "/shardkv.ShardKV/PutAppend"
	ShardKV_ShardMigration_FullMethodName = "/shardkv.ShardKV/ShardMigration"
	ShardKV_ShardGC_FullMethodName        = "/shardkv.ShardKV/ShardGC"
)

// ShardKVClient is the client API for ShardKV service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ShardKVClient interface {
	// Get RPC 请求
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
	// Put/Append RPC 请求
	PutAppend(ctx context.Context, in *PutAppendRequest, opts ...grpc.CallOption) (*PutAppendResponse, error)
	// 用于 MoveIn shard 组请求 MoveOut shard 组提供迁移分片的相关数据
	ShardMigration(ctx context.Context, in *ShardOperationRequest, opts ...grpc.CallOption) (*ShardOperationResponse, error)
	// 用于 MoveIn shard 组请求 MoveOut shard 组清理相关分片数据
	ShardGC(ctx context.Context, in *ShardOperationRequest, opts ...grpc.CallOption) (*ShardOperationResponse, error)
}

type shardKVClient struct {
	cc grpc.ClientConnInterface
}

func NewShardKVClient(cc grpc.ClientConnInterface) ShardKVClient {
	return &shardKVClient{cc}
}

func (c *shardKVClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, ShardKV_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shardKVClient) PutAppend(ctx context.Context, in *PutAppendRequest, opts ...grpc.CallOption) (*PutAppendResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PutAppendResponse)
	err := c.cc.Invoke(ctx, ShardKV_PutAppend_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shardKVClient) ShardMigration(ctx context.Context, in *ShardOperationRequest, opts ...grpc.CallOption) (*ShardOperationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ShardOperationResponse)
	err := c.cc.Invoke(ctx, ShardKV_ShardMigration_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shardKVClient) ShardGC(ctx context.Context, in *ShardOperationRequest, opts ...grpc.CallOption) (*ShardOperationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ShardOperationResponse)
	err := c.cc.Invoke(ctx, ShardKV_ShardGC_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ShardKVServer is the server API for ShardKV service.
// All implementations must embed UnimplementedShardKVServer
// for forward compatibility.
type ShardKVServer interface {
	// Get RPC 请求
	Get(context.Context, *GetRequest) (*GetResponse, error)
	// Put/Append RPC 请求
	PutAppend(context.Context, *PutAppendRequest) (*PutAppendResponse, error)
	// 用于 MoveIn shard 组请求 MoveOut shard 组提供迁移分片的相关数据
	ShardMigration(context.Context, *ShardOperationRequest) (*ShardOperationResponse, error)
	// 用于 MoveIn shard 组请求 MoveOut shard 组清理相关分片数据
	ShardGC(context.Context, *ShardOperationRequest) (*ShardOperationResponse, error)
	mustEmbedUnimplementedShardKVServer()
}

// UnimplementedShardKVServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedShardKVServer struct{}

func (UnimplementedShardKVServer) Get(context.Context, *GetRequest) (*GetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedShardKVServer) PutAppend(context.Context, *PutAppendRequest) (*PutAppendResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PutAppend not implemented")
}
func (UnimplementedShardKVServer) ShardMigration(context.Context, *ShardOperationRequest) (*ShardOperationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ShardMigration not implemented")
}
func (UnimplementedShardKVServer) ShardGC(context.Context, *ShardOperationRequest) (*ShardOperationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ShardGC not implemented")
}
func (UnimplementedShardKVServer) mustEmbedUnimplementedShardKVServer() {}
func (UnimplementedShardKVServer) testEmbeddedByValue()                 {}

// UnsafeShardKVServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ShardKVServer will
// result in compilation errors.
type UnsafeShardKVServer interface {
	mustEmbedUnimplementedShardKVServer()
}

func RegisterShardKVServer(s grpc.ServiceRegistrar, srv ShardKVServer) {
	// If the following call pancis, it indicates UnimplementedShardKVServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ShardKV_ServiceDesc, srv)
}

func _ShardKV_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShardKVServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShardKV_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShardKVServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShardKV_PutAppend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutAppendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShardKVServer).PutAppend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShardKV_PutAppend_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShardKVServer).PutAppend(ctx, req.(*PutAppendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShardKV_ShardMigration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShardOperationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShardKVServer).ShardMigration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShardKV_ShardMigration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShardKVServer).ShardMigration(ctx, req.(*ShardOperationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShardKV_ShardGC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShardOperationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShardKVServer).ShardGC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShardKV_ShardGC_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShardKVServer).ShardGC(ctx, req.(*ShardOperationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ShardKV_ServiceDesc is the grpc.ServiceDesc for ShardKV service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ShardKV_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "shardkv.ShardKV",
	HandlerType: (*ShardKVServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _ShardKV_Get_Handler,
		},
		{
			MethodName: "PutAppend",
			Handler:    _ShardKV_PutAppend_Handler,
		},
		{
			MethodName: "ShardMigration",
			Handler:    _ShardKV_ShardMigration_Handler,
		},
		{
			MethodName: "ShardGC",
			Handler:    _ShardKV_ShardGC_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/shardkv.proto",
}
