// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/shardctrler.proto

package shardctrler

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Join 请求
type JoinRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Servers       map[int32]*ServerList  `protobuf:"bytes,1,rep,name=servers,proto3" json:"servers,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // gid -> 服务器地址 列表映射
	ClientId      int64                  `protobuf:"varint,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`                                                         // 客户端唯一标识符，用于去重和追踪请求来源
	SeqId         int64                  `protobuf:"varint,3,opt,name=seq_id,json=seqId,proto3" json:"seq_id,omitempty"`                                                                  // 请求序列号，配合 client_id 实现幂等性
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinRequest) Reset() {
	*x = JoinRequest{}
	mi := &file_proto_shardctrler_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRequest) ProtoMessage() {}

func (x *JoinRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shardctrler_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRequest.ProtoReflect.Descriptor instead.
func (*JoinRequest) Descriptor() ([]byte, []int) {
	return file_proto_shardctrler_proto_rawDescGZIP(), []int{0}
}

func (x *JoinRequest) GetServers() map[int32]*ServerList {
	if x != nil {
		return x.Servers
	}
	return nil
}

func (x *JoinRequest) GetClientId() int64 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

func (x *JoinRequest) GetSeqId() int64 {
	if x != nil {
		return x.SeqId
	}
	return 0
}

type ServerList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Servers       []string               `protobuf:"bytes,1,rep,name=servers,proto3" json:"servers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerList) Reset() {
	*x = ServerList{}
	mi := &file_proto_shardctrler_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerList) ProtoMessage() {}

func (x *ServerList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shardctrler_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerList.ProtoReflect.Descriptor instead.
func (*ServerList) Descriptor() ([]byte, []int) {
	return file_proto_shardctrler_proto_rawDescGZIP(), []int{1}
}

func (x *ServerList) GetServers() []string {
	if x != nil {
		return x.Servers
	}
	return nil
}

// Join 响应
type JoinResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Err           string                 `protobuf:"bytes,1,opt,name=err,proto3" json:"err,omitempty"` // OK, ErrWrongLeader, ErrTimeout
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinResponse) Reset() {
	*x = JoinResponse{}
	mi := &file_proto_shardctrler_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinResponse) ProtoMessage() {}

func (x *JoinResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shardctrler_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinResponse.ProtoReflect.Descriptor instead.
func (*JoinResponse) Descriptor() ([]byte, []int) {
	return file_proto_shardctrler_proto_rawDescGZIP(), []int{2}
}

func (x *JoinResponse) GetErr() string {
	if x != nil {
		return x.Err
	}
	return ""
}

// Leave 请求
type LeaveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Gids          []int32                `protobuf:"varint,1,rep,packed,name=gids,proto3" json:"gids,omitempty"` // 要删除的副本组 ID 列表
	ClientId      int64                  `protobuf:"varint,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	SeqId         int64                  `protobuf:"varint,3,opt,name=seq_id,json=seqId,proto3" json:"seq_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveRequest) Reset() {
	*x = LeaveRequest{}
	mi := &file_proto_shardctrler_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveRequest) ProtoMessage() {}

func (x *LeaveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shardctrler_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveRequest.ProtoReflect.Descriptor instead.
func (*LeaveRequest) Descriptor() ([]byte, []int) {
	return file_proto_shardctrler_proto_rawDescGZIP(), []int{3}
}

func (x *LeaveRequest) GetGids() []int32 {
	if x != nil {
		return x.Gids
	}
	return nil
}

func (x *LeaveRequest) GetClientId() int64 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

func (x *LeaveRequest) GetSeqId() int64 {
	if x != nil {
		return x.SeqId
	}
	return 0
}

// Leave 响应
type LeaveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Err           string                 `protobuf:"bytes,1,opt,name=err,proto3" json:"err,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveResponse) Reset() {
	*x = LeaveResponse{}
	mi := &file_proto_shardctrler_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveResponse) ProtoMessage() {}

func (x *LeaveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shardctrler_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveResponse.ProtoReflect.Descriptor instead.
func (*LeaveResponse) Descriptor() ([]byte, []int) {
	return file_proto_shardctrler_proto_rawDescGZIP(), []int{4}
}

func (x *LeaveResponse) GetErr() string {
	if x != nil {
		return x.Err
	}
	return ""
}

// Move 请求
type MoveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Shard         int32                  `protobuf:"varint,1,opt,name=shard,proto3" json:"shard,omitempty"` // 要移动的分片编号
	Gid           int32                  `protobuf:"varint,2,opt,name=gid,proto3" json:"gid,omitempty"`     // 目标副本组 ID，将指定的分片分配给这个副本组管理
	ClientId      int64                  `protobuf:"varint,3,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	SeqId         int64                  `protobuf:"varint,4,opt,name=seq_id,json=seqId,proto3" json:"seq_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MoveRequest) Reset() {
	*x = MoveRequest{}
	mi := &file_proto_shardctrler_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveRequest) ProtoMessage() {}

func (x *MoveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shardctrler_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveRequest.ProtoReflect.Descriptor instead.
func (*MoveRequest) Descriptor() ([]byte, []int) {
	return file_proto_shardctrler_proto_rawDescGZIP(), []int{5}
}

func (x *MoveRequest) GetShard() int32 {
	if x != nil {
		return x.Shard
	}
	return 0
}

func (x *MoveRequest) GetGid() int32 {
	if x != nil {
		return x.Gid
	}
	return 0
}

func (x *MoveRequest) GetClientId() int64 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

func (x *MoveRequest) GetSeqId() int64 {
	if x != nil {
		return x.SeqId
	}
	return 0
}

// Move 响应
type MoveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Err           string                 `protobuf:"bytes,1,opt,name=err,proto3" json:"err,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MoveResponse) Reset() {
	*x = MoveResponse{}
	mi := &file_proto_shardctrler_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveResponse) ProtoMessage() {}

func (x *MoveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shardctrler_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveResponse.ProtoReflect.Descriptor instead.
func (*MoveResponse) Descriptor() ([]byte, []int) {
	return file_proto_shardctrler_proto_rawDescGZIP(), []int{6}
}

func (x *MoveResponse) GetErr() string {
	if x != nil {
		return x.Err
	}
	return ""
}

// Query 请求
type QueryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Num           int32                  `protobuf:"varint,1,opt,name=num,proto3" json:"num,omitempty"` // 期望的配置编号，-1 表示最新配置
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryRequest) Reset() {
	*x = QueryRequest{}
	mi := &file_proto_shardctrler_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRequest) ProtoMessage() {}

func (x *QueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shardctrler_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRequest.ProtoReflect.Descriptor instead.
func (*QueryRequest) Descriptor() ([]byte, []int) {
	return file_proto_shardctrler_proto_rawDescGZIP(), []int{7}
}

func (x *QueryRequest) GetNum() int32 {
	if x != nil {
		return x.Num
	}
	return 0
}

// Query 响应
type QueryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Err           string                 `protobuf:"bytes,1,opt,name=err,proto3" json:"err,omitempty"`
	Config        *Config                `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryResponse) Reset() {
	*x = QueryResponse{}
	mi := &file_proto_shardctrler_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResponse) ProtoMessage() {}

func (x *QueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shardctrler_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResponse.ProtoReflect.Descriptor instead.
func (*QueryResponse) Descriptor() ([]byte, []int) {
	return file_proto_shardctrler_proto_rawDescGZIP(), []int{8}
}

func (x *QueryResponse) GetErr() string {
	if x != nil {
		return x.Err
	}
	return ""
}

func (x *QueryResponse) GetConfig() *Config {
	if x != nil {
		return x.Config
	}
	return nil
}

// 配置信息
type Config struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Num           int32                  `protobuf:"varint,1,opt,name=num,proto3" json:"num,omitempty"`                                                                                 // 配置编号
	Shards        []int32                `protobuf:"varint,2,rep,packed,name=shards,proto3" json:"shards,omitempty"`                                                                    // 分片到 gid 的映射（固定10个元素）
	Groups        map[int32]*ServerList  `protobuf:"bytes,3,rep,name=groups,proto3" json:"groups,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // gid -> 服务器列表映射
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Config) Reset() {
	*x = Config{}
	mi := &file_proto_shardctrler_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shardctrler_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config.ProtoReflect.Descriptor instead.
func (*Config) Descriptor() ([]byte, []int) {
	return file_proto_shardctrler_proto_rawDescGZIP(), []int{9}
}

func (x *Config) GetNum() int32 {
	if x != nil {
		return x.Num
	}
	return 0
}

func (x *Config) GetShards() []int32 {
	if x != nil {
		return x.Shards
	}
	return nil
}

func (x *Config) GetGroups() map[int32]*ServerList {
	if x != nil {
		return x.Groups
	}
	return nil
}

var File_proto_shardctrler_proto protoreflect.FileDescriptor

const file_proto_shardctrler_proto_rawDesc = "" +
	"\n" +
	"\x17proto/shardctrler.proto\x12\vshardctrler\"\xd7\x01\n" +
	"\vJoinRequest\x12?\n" +
	"\aservers\x18\x01 \x03(\v2%.shardctrler.JoinRequest.ServersEntryR\aservers\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\x03R\bclientId\x12\x15\n" +
	"\x06seq_id\x18\x03 \x01(\x03R\x05seqId\x1aS\n" +
	"\fServersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12-\n" +
	"\x05value\x18\x02 \x01(\v2\x17.shardctrler.ServerListR\x05value:\x028\x01\"&\n" +
	"\n" +
	"ServerList\x12\x18\n" +
	"\aservers\x18\x01 \x03(\tR\aservers\" \n" +
	"\fJoinResponse\x12\x10\n" +
	"\x03err\x18\x01 \x01(\tR\x03err\"V\n" +
	"\fLeaveRequest\x12\x12\n" +
	"\x04gids\x18\x01 \x03(\x05R\x04gids\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\x03R\bclientId\x12\x15\n" +
	"\x06seq_id\x18\x03 \x01(\x03R\x05seqId\"!\n" +
	"\rLeaveResponse\x12\x10\n" +
	"\x03err\x18\x01 \x01(\tR\x03err\"i\n" +
	"\vMoveRequest\x12\x14\n" +
	"\x05shard\x18\x01 \x01(\x05R\x05shard\x12\x10\n" +
	"\x03gid\x18\x02 \x01(\x05R\x03gid\x12\x1b\n" +
	"\tclient_id\x18\x03 \x01(\x03R\bclientId\x12\x15\n" +
	"\x06seq_id\x18\x04 \x01(\x03R\x05seqId\" \n" +
	"\fMoveResponse\x12\x10\n" +
	"\x03err\x18\x01 \x01(\tR\x03err\" \n" +
	"\fQueryRequest\x12\x10\n" +
	"\x03num\x18\x01 \x01(\x05R\x03num\"N\n" +
	"\rQueryResponse\x12\x10\n" +
	"\x03err\x18\x01 \x01(\tR\x03err\x12+\n" +
	"\x06config\x18\x02 \x01(\v2\x13.shardctrler.ConfigR\x06config\"\xbf\x01\n" +
	"\x06Config\x12\x10\n" +
	"\x03num\x18\x01 \x01(\x05R\x03num\x12\x16\n" +
	"\x06shards\x18\x02 \x03(\x05R\x06shards\x127\n" +
	"\x06groups\x18\x03 \x03(\v2\x1f.shardctrler.Config.GroupsEntryR\x06groups\x1aR\n" +
	"\vGroupsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12-\n" +
	"\x05value\x18\x02 \x01(\v2\x17.shardctrler.ServerListR\x05value:\x028\x012\x87\x02\n" +
	"\vShardCtrler\x12;\n" +
	"\x04Join\x12\x18.shardctrler.JoinRequest\x1a\x19.shardctrler.JoinResponse\x12>\n" +
	"\x05Leave\x12\x19.shardctrler.LeaveRequest\x1a\x1a.shardctrler.LeaveResponse\x12;\n" +
	"\x04Move\x12\x18.shardctrler.MoveRequest\x1a\x19.shardctrler.MoveResponse\x12>\n" +
	"\x05Query\x12\x19.shardctrler.QueryRequest\x1a\x1a.shardctrler.QueryResponseB\x1bZ\x19./shardctrler;shardctrlerb\x06proto3"

var (
	file_proto_shardctrler_proto_rawDescOnce sync.Once
	file_proto_shardctrler_proto_rawDescData []byte
)

func file_proto_shardctrler_proto_rawDescGZIP() []byte {
	file_proto_shardctrler_proto_rawDescOnce.Do(func() {
		file_proto_shardctrler_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_shardctrler_proto_rawDesc), len(file_proto_shardctrler_proto_rawDesc)))
	})
	return file_proto_shardctrler_proto_rawDescData
}

var file_proto_shardctrler_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_proto_shardctrler_proto_goTypes = []any{
	(*JoinRequest)(nil),   // 0: shardctrler.JoinRequest
	(*ServerList)(nil),    // 1: shardctrler.ServerList
	(*JoinResponse)(nil),  // 2: shardctrler.JoinResponse
	(*LeaveRequest)(nil),  // 3: shardctrler.LeaveRequest
	(*LeaveResponse)(nil), // 4: shardctrler.LeaveResponse
	(*MoveRequest)(nil),   // 5: shardctrler.MoveRequest
	(*MoveResponse)(nil),  // 6: shardctrler.MoveResponse
	(*QueryRequest)(nil),  // 7: shardctrler.QueryRequest
	(*QueryResponse)(nil), // 8: shardctrler.QueryResponse
	(*Config)(nil),        // 9: shardctrler.Config
	nil,                   // 10: shardctrler.JoinRequest.ServersEntry
	nil,                   // 11: shardctrler.Config.GroupsEntry
}
var file_proto_shardctrler_proto_depIdxs = []int32{
	10, // 0: shardctrler.JoinRequest.servers:type_name -> shardctrler.JoinRequest.ServersEntry
	9,  // 1: shardctrler.QueryResponse.config:type_name -> shardctrler.Config
	11, // 2: shardctrler.Config.groups:type_name -> shardctrler.Config.GroupsEntry
	1,  // 3: shardctrler.JoinRequest.ServersEntry.value:type_name -> shardctrler.ServerList
	1,  // 4: shardctrler.Config.GroupsEntry.value:type_name -> shardctrler.ServerList
	0,  // 5: shardctrler.ShardCtrler.Join:input_type -> shardctrler.JoinRequest
	3,  // 6: shardctrler.ShardCtrler.Leave:input_type -> shardctrler.LeaveRequest
	5,  // 7: shardctrler.ShardCtrler.Move:input_type -> shardctrler.MoveRequest
	7,  // 8: shardctrler.ShardCtrler.Query:input_type -> shardctrler.QueryRequest
	2,  // 9: shardctrler.ShardCtrler.Join:output_type -> shardctrler.JoinResponse
	4,  // 10: shardctrler.ShardCtrler.Leave:output_type -> shardctrler.LeaveResponse
	6,  // 11: shardctrler.ShardCtrler.Move:output_type -> shardctrler.MoveResponse
	8,  // 12: shardctrler.ShardCtrler.Query:output_type -> shardctrler.QueryResponse
	9,  // [9:13] is the sub-list for method output_type
	5,  // [5:9] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_proto_shardctrler_proto_init() }
func file_proto_shardctrler_proto_init() {
	if File_proto_shardctrler_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_shardctrler_proto_rawDesc), len(file_proto_shardctrler_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_shardctrler_proto_goTypes,
		DependencyIndexes: file_proto_shardctrler_proto_depIdxs,
		MessageInfos:      file_proto_shardctrler_proto_msgTypes,
	}.Build()
	File_proto_shardctrler_proto = out.File
	file_proto_shardctrler_proto_goTypes = nil
	file_proto_shardctrler_proto_depIdxs = nil
}
